apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: PORT
          value: "5432"
        - name: POSTGRES_DB
          value: petsdc_buying
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          value: justuskovats-wildenradt
        image: postgres:10.4
        name: database
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: database-claim0
      restartPolicy: Always
      volumes:
      - name: database-claim0
        persistentVolumeClaim:
          claimName: database-claim0
status: {}
