version: '3'
services:
  buying:
    image: justuskw/buying-petsdc:v31
    depends_on:
      - 'database'
      - 'redis'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - '8000:8000'
    # environment:
    #   DATABASE_URL: postgres://postgres:password@database:5432/petsdc_buying    
    networks:
      - webnet
 
  database:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'petsdc_buying'
      PORT: '5432'
    volumes:
      # - './data:/data'
      - './dockerSchema.sql:/dockerSchema.sql'
    networks:
      - webnet
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: