version: '3'

services:
  buying:
    image: justuskw/petsdc-swarm:test
    depends_on:
      - 'database'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - '8000:8000'
    networks:
      - webnet

  database:
    image: postgres:10.4
    environment:
      POSTGRES_USER: 'justuskovats-wildenradt'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'petsdc_buying'
      PORT: 5432
    volumes:
      - ../data:/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
networks:
  webnet: