version: '3'
services:
  buying:
    image: justuskw/buying-petsdc:last1
    depends_on:
      - 'database'
      - 'redis'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - '8000:8000'
    networks:
      - default
 
  database:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'petsdc_buying'
      PORT: '5432'
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - default